setwd("/home/terhorst/Dropbox/Michigan/Teaching/stats/306/lectures/lectures/lecture02")
mil <- tibble(age=millenials$age, state=millenials$state, q1=millenials$q1, 
              q8a=millenials$q8a, 
              q8b=millenials$q8b, 
              q8c=millenials$q8c, 
              q8d=millenials$q8d, 
              q8e=millenials$q8e, 
              q8f=millenials$q8f, 
              q8g=millenials$q8g, 
              q8h=millenials$q8h, 
              q19=millenials$q19,
              q20=millenials$q20,
              q25=millenials$q25,
              q25a=millenials$q25a,
              q36=millenials$q36,
              q41=millenials$q41,
              q44a=millenials$q44a,
              q44b=millenials$q44b,
              q44c=millenials$q44c,
              q44d=millenials$q44d,
              q44g=millenials$q44g,
              q44i=millenials$q44i, 
              q45a=millenials$q45a, 
              q46=millenials$q46, 
              employ=millenials$employ,
              lwp=millenials$lwp3, 
              finan=millenials$finan, 
              home2=millenials$home2,
              educ=millenials$educ,
              health=millenials$health)
save(mil, file="millennials.RData")

